name: test_env_xapres
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0.*
  - pandas=2.2.*
  - xarray>=2024.10
  - zarr
  - numcodecs>=0.12
  - dask
  - aiohttp<3.9
  - scipy
  - netcdf4
  - fsspec
  - gcsfs
  - pytest
  - tqdm
  - pytest-cov
  - coverage
  - typing_extensions>=4.10,<5
