name: test_env_xapres
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0.*
  - pandas=2.2.*
  - xarray>=2024.10
  - dask
  - zarr
  - scipy
  - netcdf4
  - fsspec
  - gcsfs
  - pytest
  - tqdm
  - ipympl
  - pytest-cov
  - coverage
  - pip
  - pip:
      - codecov