name: test_env_xapres
channels:
  - conda-forge
dependencies:
  - python=3.11
  ############## These will have to be adjusted to your specific project
  - pytest
  - gcsfs
  - numpy
  - xarray
  - pandas
  - tqdm
  - pip
  - zarr
  - dask
  - scipy
  - pip:
    - ipympl
    - sounddevice
    - soundfile
    - bas-apres
    - codecov
    - pytest-cov
    - coverage[toml]