name: test_env_xapres
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.*
  - xarray>=2024.10
  - numpy<2
  - zarr>=2.15,<3
  - numcodecs>=0.11,<0.12     # stable with zarr 2.x
  - c-blosc=1.21.*            # ensure correct C-Blosc v1
  - typing_extensions>=4.8,<5
  - dask
  - scipy
  - netcdf4
  - fsspec
  - gcsfs
  - pytest
  - tqdm
  - ipympl
  - pytest-cov
  - coverage
  - pip
  - pip:
      - codecov