name: Tests
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if ci/environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/environment-py${{ matrix.python-version }}.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          # mamba-version: "*" # activate this to build with mamba.
          # channels: conda-forge, defaults # These need to be specified to use mamba
          # channel-priority: true
          environment-file: ci/environment-py${{ matrix.python-version }}.yml

          activate-environment: test_env_xapres
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Set up conda environment
        shell: bash -l {0}
        run: |
          python -m pip install -e . --no-deps --force-reinstall
      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest -k "not sonify and not dat_file_loading" --cov=./ --cov-report=xml   
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md    


